GET http://localhost:3000/api/cats

###

GET http://localhost:3000/api/cats/3

###

POST http://localhost:3000/api/cats
Content-Type: application/json

{
    "name": "Puss in Boots",
    "description": "Puss in Boots is a main character in the Shrek franchise, also being portrayed as the title character and protagonist of the film Puss in Boots (2011).",
    "color": "orange",
    "breed": "mixed"
}

###

PUT http://localhost:3000/api/cats/1
Content-Type: application/json

{
    "name": "Toulouse",
    "description": "Toulouse is a major character in The Aristocats. He is an orange furred kitten who is the oldest child and eldest son of Duchess and the older brother of Marie and Berlioz",
    "color": "orange",
    "breed": "turkish angora"
}

###
 
DELETE http://localhost:3000/api/cats/3



